We are goin to learn numpy

Learning numpy creating different types of array

In [ ]:
import numpy as np
from numpy import random

array1=np.array([[1, 2],
              [3, 4]])
array2=np.array([[4, 3],
              [2, 1]], dtype='uint8')
array1,array2
#print type
print("Array is of type: ", type(array1))
# Print dimension (axes)
print("No. of dimensions: ", array1.ndim)
# Print shape
print("Shape of array: ", array2.shape)
# Printing total number of elements
print("Size of array: ", array2.size)
 # Printing type of elements in array
print("Array stores elements of type: ", array2.dtype)
#create array of zeros 3x4 shape
zeroArray = np.zeros((3, 4))
print(zeroArray)
oneArray = np.ones((3, 4), dtype='int8')
print(oneArray)
constArray = np.full((3, 3), 6, dtype = 'float32')
print(constArray)
list1=[2,4,5,7,8,9]
changedArray= np.array(list1).astype('float32')
print(changedArray)
chanArray=changedArray.reshape([2,3])
print(chanArray)
randomArray = random.randint(100, size=(3, 5))
print(randomArray)

Operations with arrays and Data types

In [37]:
array3= array1+array2
array3
array3=array1-array2
print(array3)
array3+1
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 

# Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)
 
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)
 
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)
 
# Transpose of Array (The transpose of a matrix is simply a flipped version of the original matrix.)
# using In-built function 'T'
print(arr1)
Trans_arr = arr1.T
print("\nTranspose of Array: ")
print(Trans_arr)
# using flatten method
print("flatten array",arr1.flatten())
 

[[-3 -1]
 [ 1  3]]
Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]

Addition of Array elements: 
19.0

Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 7.]
 [2. 6.]]

Transpose of Array: 
[[4. 2.]
 [7. 6.]]
flatten array [4. 7. 2. 6.]
